# Generated by Django 5.1.7 on 2025-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idcuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(max_length=25)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
