# Generated by Django 5.2 on 2025-05-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
        ('donador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='donador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donador.donador'),
        ),
        migrations.DeleteModel(
            name='Donador',
        ),
    ]
