# Generated by Django 5.1.7 on 2025-04-07 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonia', '0001_initial'),
        ('coordenada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numInterior', models.CharField(max_length=10)),
                ('numExterior', models.CharField(max_length=10)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonia.colonia')),
                ('coordenadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenada.coordenada')),
            ],
        ),
    ]
