# Generated by Django 5.1.7 on 2025-06-05 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0002_alter_cita_donador_delete_donador'),
        ('donador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateField(auto_now_add=True)),
                ('cantidad_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lugar_donacion', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('dono', models.BooleanField(default=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donador.donador')),
            ],
        ),
    ]
